### ISSUE TITLE
git ignore yarn.lock

### ISSUE THREAD

**Issue by arnaudjuracek** [brocessing/bro-start-nano#2]

**Comment by arnaudjuracek** [comment]
`¯\_(ツ)_/¯`
https://github.com/yarnpkg/yarn/issues/1583

**Comment by Younes-sh** [comment]
You should never, ever "gitignore" your lock files(package-lock.json and/or yarn.lock)! Even when installing using npm install, it generates a notice that we "should commit this file". The lock files are used to "lock" the versions of the dependencies used in the project and also of the dependencies used by the top-level packages.

**Comment by arnaudjuracek** [comment]
Thank you for re-opening an issue on a project dead for 5 years, without understanding that it has already been solved.
